services:
  - type: web
    name: maharaja-bellerose-raffle
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: admin123secure
      - key: DATABASE_URL
        fromDatabase:
          name: maharaja-raffle-db
          property: connectionString

databases:
  - name: maharaja-raffle-db
    plan: free
    ipAllowList: []